Repository PinTogether/backend, pull requests merged in 2024-04, with the labels that each got.

#167 Feature 검색 기록 삭제#166
  src/main/java/com/pintogether/backend/controller/SearchController.java
  src/main/java/com/pintogether/backend/entity/SearchHistory.java
  src/main/java/com/pintogether/backend/service/SearchService.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
Labels: enhancement

#171 Feat: 소켓서비스 수정, 알림 목록 조회 api 및 새로운 알림 갯수 조회 api 완성
  src/main/java/com/pintogether/backend/controller/CollectionController.java
  src/main/java/com/pintogether/backend/controller/MemberController.java
  src/main/java/com/pintogether/backend/dto/ShowAlertCntResponseDTO.java
  src/main/java/com/pintogether/backend/dto/ShowNotificationResponseDTO.java
  src/main/java/com/pintogether/backend/dto/ShowNotificationsResponseDTO.java
  src/main/java/com/pintogether/backend/dto/ShowOtherMemberResponseDTO.java
  src/main/java/com/pintogether/backend/entity/Member.java
  src/main/java/com/pintogether/backend/entity/Notification.java
  src/main/java/com/pintogether/backend/entity/enums/NotificationType.java
  src/main/java/com/pintogether/backend/repository/NotificationRepository.java
  src/main/java/com/pintogether/backend/service/MemberService.java
  src/main/java/com/pintogether/backend/service/NotificationService.java
  src/main/java/com/pintogether/backend/websocket/WebSocketService.java
Labels: enhancement, Fix

#172 refector: 이미 선언해놓은 now 변수 사용하도록 코드 수정
  src/main/java/com/pintogether/backend/controller/MemberController.java
Labels: Fix

#174 fix: pin-review-updating #173
  src/main/java/com/pintogether/backend/service/PinService.java
Labels: Fix

#180 chores: add logging in securityfilter
  src/main/java/com/pintogether/backend/auth/JwtAuthenticationFilter.java
Labels: chores

#181 chores: add logging in securityfilter #179
  src/main/java/com/pintogether/backend/auth/JwtAuthenticationFilter.java
Labels: chores

#182 chores: editing logging
  src/main/java/com/pintogether/backend/auth/JwtAuthenticationFilter.java
Labels: chores

#184 fix: restentrypoint send for whole error not only for 401
  src/main/java/com/pintogether/backend/auth/RestAuthenticationEntryPoint.java
Labels: Fix

#186 Fix security filter #185
  src/main/java/com/pintogether/backend/auth/JwtAuthenticationFilter.java
  src/main/java/com/pintogether/backend/auth/RestAuthenticationEntryPoint.java
  src/main/java/com/pintogether/backend/config/SecurityConfig.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
Labels: Fix

#188 fix: security filter update endpoint #187
  src/main/java/com/pintogether/backend/auth/JwtAuthenticationFilter.java
  src/main/java/com/pintogether/backend/config/SecurityConfig.java
  src/main/java/com/pintogether/backend/controller/PlaceController.java
  src/main/java/com/pintogether/backend/controller/SearchController.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
Labels: Fix

#193 fix: complaint null guard
  src/main/java/com/pintogether/backend/controller/ComplaintController.java
  src/main/java/com/pintogether/backend/service/ComplaintService.java
Labels: Fix

#196 fix: update member save #194
  src/main/java/com/pintogether/backend/service/MemberService.java
Labels: Fix

#198 feat: search-by-screen add filter option: pin, place #197
  src/main/java/com/pintogether/backend/controller/SearchController.java
  src/main/java/com/pintogether/backend/repository/PinRepository.java
  src/main/java/com/pintogether/backend/repository/PlaceRepository.java
  src/main/java/com/pintogether/backend/service/SearchService.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
  src/main/java/com/pintogether/backend/util/CoordinateConverter.java
Labels: enhancement

#207 Fix: 알림 목록 조회시 objectId 함께 반환하도록 수정 #206
  src/main/java/com/pintogether/backend/controller/MemberController.java
  src/main/java/com/pintogether/backend/dto/ShowNotificationResponseDTO.java
  src/main/java/com/pintogether/backend/entity/Notification.java
  src/main/java/com/pintogether/backend/service/NotificationService.java
Labels: Fix

#213 Bug: 자기 자신을 팔로우하는 경우 예외처리 함
  src/main/java/com/pintogether/backend/service/FollowingService.java
Labels: bug

#218 refactor: @ThisMember 적용
  src/main/java/com/pintogether/backend/controller/CollectionController.java
  src/main/java/com/pintogether/backend/controller/MemberController.java
Labels: Refactoring
