Repository PinTogether/backend, pull requests merged in 2024-03, with the labels that each got.

#28 fix: cicd test dependency; add ankane/setup-mariadb@v1
  .github/workflows/deploy.yml
  .gitignore
Labels: bug

#29 fix: cicd; edit CI except for test
  .github/workflows/deploy.yml
  src/test/java/com/pintogether/backend/BackendApplicationTests.java
  src/test/java/com/pintogether/backend/repository/PinRepositoryTest.java
Labels: bug

#34 fix: cicd test cicd; test comment out
  src/main/resources/index.html
  src/test/java/com/pintogether/backend/entity/FollowingTest.java
  src/test/java/com/pintogether/backend/entity/StarTest.java
  src/test/java/com/pintogether/backend/repository/PinRepositoryTest.java
  src/test/java/com/pintogether/backend/repository/PlaceRepositoryTest.java
Labels: bug

#36 fix: cicd; types_max_hash_size
  .platform/nginx/conf.d/10-types-hash.conf
Labels: bug

#37 feat: cicd; edit deploy
  .DS_Store
  .github/workflows/deploy.yml
Labels: bug

#39 fix: cicd
  .github/workflows/deploy.yml
Labels: bug

#41 fix: cicd
  src/main/java/com/pintogether/backend/entity/BaseUpdatedAtEntity.java
Labels: bug

#42 fix: cicd test
  .github/workflows/deploy.yml
Labels: bug

#43 fix: cicd test
  .github/workflows/deploy.yml
Labels: bug

#44 fix: cicd test; edit build.gradle
  build.gradle
Labels: bug

#45 fix: mariadb parameters setting; wait_time, max_connections
  .github/workflows/deploy.yml
Labels: bug

#46 fix: cicd; submodule pull
  .github/workflows/deploy.yml
Labels: bug

#47 fix: cicd; remove *.jar from gitignore
  .gitignore
Labels: bug

#48 fix: cicd; remove *.jar from gitignore
  .github/workflows/deploy.yml
Labels: bug

#49 fix: cicd; submodule settings
  .github/workflows/deploy.yml
Labels: bug

#50 fix: cicd; add env logging
  .github/workflows/deploy.yml
Labels: bug

#51 fix: cicd; add cp command: application.properties
  .github/workflows/deploy.yml
Labels: bug

#52 fix: cicd; decomment cp command in build.gradle
  .github/workflows/deploy.yml
  build.gradle
Labels: bug

#53 fix: cicd; types_hash_max_size 4096 -> 1024
  .platform/nginx/conf.d/10-types-hash.conf
Labels: bug

#54 fix: cicd; types_hash_max_size 1024 -> 2048
  .platform/nginx/conf.d/10-types-hash.conf
Labels: bug

#55 fix: cicd; types_hash_bucket_size 128
  .platform/nginx/conf.d/10-types-hash.conf
  src/main/java/com/pintogether/backend/controller/TestController.java
Labels: bug

#56 fix: cicd
  .platform/nginx/conf.d/10-types-hash.conf
  src/main/java/com/pintogether/backend/controller/MainController.java
Labels: bug

#57 fix: cicd complete
  .github/workflows/deploy.yml
Labels: bug

#58 fix: cicd complete
  .github/workflows/deploy.yml
Labels: bug

#59 fix: cicd; edit git pull strategy
  .github/workflows/deploy.yml
Labels: bug

#60 fix: cicd complete
  .github/workflows/deploy.yml
Labels: bug

#62 fix: cicd finish
  src/main/java/com/pintogether/backend/auth/OAuth2LoginSuccessHandler.java
Labels: bug

#64 Feature: coordinate-converter
  build.gradle
  src/main/java/com/pintogether/backend/controller/TestController.java
  src/main/java/com/pintogether/backend/dto/CoordinateDto.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
  src/main/java/com/pintogether/backend/util/CoordinateConverter.java
Labels: enhancement

#65 Feat: Search Place interface
  src/main/java/com/pintogether/backend/dto/SearchPlaceResponseDto.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
Labels: enhancement

#67 fix: submodule git pull strategy: recursive
  .github/workflows/deploy.yml
Labels: bug

#69 feat: cicd;
  .github/workflows/deploy.yml
Labels: enhancement

#70 feat: cicd; rebase
  .github/workflows/deploy.yml
Labels: bug

#73 feat: security; edit jwtfilter #72
  .DS_Store
  src/main/java/com/pintogether/backend/auth/JwtAuthenticationFilter.java
  src/main/java/com/pintogether/backend/auth/OAuth2LoginSuccessHandler.java
  src/main/java/com/pintogether/backend/config/SecurityConfig.java
Labels: enhancement

#74 Feature/#24 담당 api 구현
  src/main/java/com/pintogether/backend/dto/CollectionRequestDTO.java
  src/main/java/com/pintogether/backend/dto/CoordinateDTO.java
  src/main/java/com/pintogether/backend/dto/MemberUpdateRequest.java
  src/main/java/com/pintogether/backend/dto/SearchPlaceResponseDTO.java
  src/main/java/com/pintogether/backend/exception/CustomException.java
  src/main/java/com/pintogether/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/pintogether/backend/model/ApiResponse.java
  src/main/java/com/pintogether/backend/model/StatusCode.java
Labels: enhancement

#75 Fix: GlobalExceptionHanlder, CustomException 수정
  src/main/java/com/pintogether/backend/exception/CustomException.java
  src/main/java/com/pintogether/backend/exception/GlobalExceptionHandler.java
Labels: Fix

#76 Feature/#24 담당 api 구현
  src/main/java/com/pintogether/backend/controller/MemberController.java
  src/main/java/com/pintogether/backend/controller/SearchController.java
  src/main/java/com/pintogether/backend/controller/TestController.java
  src/main/java/com/pintogether/backend/dto/ShowCollectionResponseDTO.java
  src/main/java/com/pintogether/backend/dto/ShowMemberResponseDTO.java
  src/main/java/com/pintogether/backend/dto/ShowOtherMemberResponseDTO.java
  src/main/java/com/pintogether/backend/dto/ShowSimpleMemberResponseDTO.java
  src/main/java/com/pintogether/backend/dto/UpdateMemberRequestDTO.java
  src/main/java/com/pintogether/backend/dto/UpdateMemberResponseDTO.java
  src/main/java/com/pintogether/backend/entity/Member.java
  src/main/java/com/pintogether/backend/entity/Place.java
  src/main/java/com/pintogether/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/pintogether/backend/repository/CollectionRepository.java
  src/main/java/com/pintogether/backend/repository/FollowingRepository.java
  src/main/java/com/pintogether/backend/repository/InterestingCollectionRepository.java
  src/main/java/com/pintogether/backend/repository/MemberRepository.java
  src/main/java/com/pintogether/backend/service/CollectionService.java
  src/main/java/com/pintogether/backend/service/FollowingService.java
  src/main/java/com/pintogether/backend/service/InterestingCollectionService.java
  src/main/java/com/pintogether/backend/service/MemberService.java
  src/main/java/com/pintogether/backend/service/SearchService.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
  src/main/java/com/pintogether/backend/util/CoordinateConverter.java
Labels: enhancement

#77 Feat: CustomStatusMessage 추가
  src/main/java/com/pintogether/backend/controller/MemberController.java
  src/main/java/com/pintogether/backend/model/CustomStatusMessage.java
Labels: enhancement

#78 Fix: ExceptionHandler, ApiResponse가 httpResponse status code도 갱신하도록 수정함
  src/main/java/com/pintogether/backend/controller/MemberController.java
  src/main/java/com/pintogether/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/pintogether/backend/model/ApiResponse.java
Labels: Fix

#80 Fix: makeResponse()를 ApiResponse()의 정적 메서드로 추가
  src/main/java/com/pintogether/backend/controller/CollectionController.java
  src/main/java/com/pintogether/backend/controller/MemberController.java
  src/main/java/com/pintogether/backend/dto/CollectionRequestDTO.java
  src/main/java/com/pintogether/backend/dto/CreateCollectionRequestDTO.java
  src/main/java/com/pintogether/backend/dto/ShowCollectionResponseDTO.java
  src/main/java/com/pintogether/backend/dto/UpdateCollectionRequestDTO.java
  src/main/java/com/pintogether/backend/entity/Collection.java
  src/main/java/com/pintogether/backend/entity/enums/InterestType.java
  src/main/java/com/pintogether/backend/model/ApiResponse.java
  src/main/java/com/pintogether/backend/model/CustomStatusMessage.java
  src/main/java/com/pintogether/backend/model/StatusCode.java
  src/main/java/com/pintogether/backend/repository/CollectionRepository.java
  src/main/java/com/pintogether/backend/repository/InterestingCollectionRepository.java
  src/main/java/com/pintogether/backend/service/CollectionService.java
  src/main/java/com/pintogether/backend/service/FollowingService.java
  src/main/java/com/pintogether/backend/service/InterestingCollectionService.java
  src/main/java/com/pintogether/backend/service/MemberService.java
Labels: Fix

#86 Feature/#85 colleciton comment api 및 presigned url api 구현
  build.gradle
  src/main/java/com/pintogether/backend/config/AmazonS3Config.java
  src/main/java/com/pintogether/backend/config/WebConfig.java
  src/main/java/com/pintogether/backend/controller/CollectionController.java
  src/main/java/com/pintogether/backend/controller/MemberController.java
  src/main/java/com/pintogether/backend/customAnnotations/CurrentCollection.java
  src/main/java/com/pintogether/backend/customAnnotations/CurrentCollectionComment.java
  src/main/java/com/pintogether/backend/dto/CreateCollectionCommentRequestDTO.java
  src/main/java/com/pintogether/backend/dto/CreateCollectionRequestDTO.java
  src/main/java/com/pintogether/backend/dto/S3CollectionThumbnailRequestDTO.java
  src/main/java/com/pintogether/backend/dto/S3MemberAvatarRequestDTO.java
  src/main/java/com/pintogether/backend/dto/ShowCollectionCommentResponseDTO.java
  src/main/java/com/pintogether/backend/dto/UpdateMemberRequestDTO.java
  src/main/java/com/pintogether/backend/entity/BaseEntity.java
  src/main/java/com/pintogether/backend/entity/Collection.java
  src/main/java/com/pintogether/backend/entity/CollectionComment.java
  src/main/java/com/pintogether/backend/entity/CollectionTag.java
  src/main/java/com/pintogether/backend/entity/Member.java
  src/main/java/com/pintogether/backend/handlerMethodArgumentResolver/CollectionArgumentResolver.java
  src/main/java/com/pintogether/backend/handlerMethodArgumentResolver/CollectionCommentArgumentResolver.java
  src/main/java/com/pintogether/backend/model/CustomStatusMessage.java
  src/main/java/com/pintogether/backend/repository/CollectionCommentRepository.java
  src/main/java/com/pintogether/backend/repository/CollectionRepository.java
  src/main/java/com/pintogether/backend/repository/FollowingRepository.java
  src/main/java/com/pintogether/backend/repository/InterestingCollectionRepository.java
  src/main/java/com/pintogether/backend/service/AmazonS3Service.java
  src/main/java/com/pintogether/backend/service/CollectionCommentService.java
  src/main/java/com/pintogether/backend/service/CollectionService.java
  src/main/java/com/pintogether/backend/service/DomainType.java
  src/main/java/com/pintogether/backend/service/FollowingService.java
  src/main/java/com/pintogether/backend/service/MemberService.java
Labels: enhancement

#102 Feat: S3이미지 삭제 서비스 구현 및 컬렉션과 멤버 수정 서비스에 추가
  src/main/java/com/pintogether/backend/service/AmazonS3Service.java
  src/main/java/com/pintogether/backend/service/CollectionService.java
  src/main/java/com/pintogether/backend/service/MemberService.java
Labels: enhancement

#108 Fix 멤버와 컬렉션 생성시 기본이미지로 초기화하기 #103
  src/main/java/com/pintogether/backend/auth/OAuth2LoginSuccessHandler.java
  src/main/java/com/pintogether/backend/controller/CollectionController.java
  src/main/java/com/pintogether/backend/dto/CreateCollectionRequestDTO.java
  src/main/java/com/pintogether/backend/entity/Member.java
  src/main/java/com/pintogether/backend/service/CollectionService.java
  src/main/java/com/pintogether/backend/service/MemberService.java
Labels: Fix

#112 Fix: 좋아요 top 컬렉션 조회 API 비회원 접근 가능하게 수정
  src/main/java/com/pintogether/backend/controller/CollectionController.java
Labels: Fix

#117 feat: 로그인 필요시 401반환 #116
  src/main/java/com/pintogether/backend/auth/JwtAuthenticationFilter.java
  src/main/java/com/pintogether/backend/auth/RestAuthenticationEntryPoint.java
  src/main/java/com/pintogether/backend/config/SecurityConfig.java
  src/main/java/com/pintogether/backend/controller/MainController.java
  src/main/java/com/pintogether/backend/controller/PinController.java
  src/main/java/com/pintogether/backend/controller/PlaceController.java
  src/main/java/com/pintogether/backend/dto/CreateSelectedPinsRequestDTO.java
  src/main/java/com/pintogether/backend/dto/DeleteSelectedPinsRequestDTO.java
  src/main/java/com/pintogether/backend/dto/PinDTO.java
  src/main/java/com/pintogether/backend/dto/PinsResponseDTO.java
  src/main/java/com/pintogether/backend/dto/S3PinImageRequestDTO.java
  src/main/java/com/pintogether/backend/dto/ShowPinImagesResponseDTO.java
  src/main/java/com/pintogether/backend/dto/UpdatePinReqeustDTO.java
  src/main/java/com/pintogether/backend/entity/Pin.java
  src/main/java/com/pintogether/backend/model/ApiResponse.java
  src/main/java/com/pintogether/backend/repository/PinRepository.java
  src/main/java/com/pintogether/backend/service/PinService.java
  src/main/java/com/pintogether/backend/service/PlaceService.java
Labels: enhancement

#119 Fix: collection 생성 API 반환 값 수정
  src/main/java/com/pintogether/backend/controller/CollectionController.java
  src/main/java/com/pintogether/backend/dto/CreateCollectionRequestDTO.java
  src/main/java/com/pintogether/backend/dto/CreateCollectionResponseDTO.java
  src/main/java/com/pintogether/backend/service/AmazonS3Service.java
  src/main/java/com/pintogether/backend/service/CollectionService.java
Labels: Fix

#118 feat: Pins, Place 엔티티에 대한 모든 API 2 #113;
  src/main/java/com/pintogether/backend/controller/MainController.java
  src/main/java/com/pintogether/backend/controller/PinController.java
  src/main/java/com/pintogether/backend/controller/PlaceController.java
  src/main/java/com/pintogether/backend/controller/SearchController.java
  src/main/java/com/pintogether/backend/dto/PinsResponseDTO.java
  src/main/java/com/pintogether/backend/dto/ShowPinResponseDTO.java
  src/main/java/com/pintogether/backend/dto/ShowPlaceResponseDTO.java
  src/main/java/com/pintogether/backend/dto/UpdatePinReqeustDTO.java
  src/main/java/com/pintogether/backend/entity/Pin.java
  src/main/java/com/pintogether/backend/entity/PinTag.java
  src/main/java/com/pintogether/backend/entity/Place.java
  src/main/java/com/pintogether/backend/service/SearchService.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
Labels: enhancement

#131 refactor: ShowPinResponseDTO; add writerId in this DTO, updated relat… #130
  src/main/java/com/pintogether/backend/dto/ShowPinResponseDTO.java
  src/main/java/com/pintogether/backend/entity/Pin.java
Labels: Rename

#134 feat: add placeId in ShowPinResponseDTO, permit search for anyone#133
  src/main/java/com/pintogether/backend/auth/JwtAuthenticationFilter.java
  src/main/java/com/pintogether/backend/config/SecurityConfig.java
  src/main/java/com/pintogether/backend/dto/ShowPinResponseDTO.java
  src/main/java/com/pintogether/backend/entity/Pin.java
Labels: enhancement

#140 Feature/complaint #135
  src/main/java/com/pintogether/backend/config/ProjectConfig.java
  src/main/java/com/pintogether/backend/controller/ComplaintController.java
  src/main/java/com/pintogether/backend/dto/CreateComplaintRequestDTO.java
  src/main/java/com/pintogether/backend/dto/ShowComplaintResponseDTO.java
  src/main/java/com/pintogether/backend/entity/Complaint.java
  src/main/java/com/pintogether/backend/entity/enums/PlatformType.java
  src/main/java/com/pintogether/backend/entity/enums/Progress.java
  src/main/java/com/pintogether/backend/repository/ComplaintRepository.java
  src/main/java/com/pintogether/backend/service/ComplaintService.java
Labels: enhancement

#142 Fix: 컬렉션 태그 업데이트 정상 작동 되도록 수정
  src/main/java/com/pintogether/backend/service/CollectionService.java
Labels: Fix

#153 Fix/pin send pin #152
  src/main/java/com/pintogether/backend/controller/PinController.java
  src/main/java/com/pintogether/backend/dto/CreatePinResponseDTO.java
  src/main/java/com/pintogether/backend/model/ApiResponse.java
  src/main/java/com/pintogether/backend/service/PinService.java
Labels: Fix

#162 fix: add writerId in ShowPinResponseDTO #161
  src/main/java/com/pintogether/backend/entity/Pin.java
Labels: Fix

#165 Feature 검색 기록 중복은 저장안함 #164
  src/main/java/com/pintogether/backend/controller/SearchController.java
  src/main/java/com/pintogether/backend/repository/SearchHistoryRepository.java
  src/main/java/com/pintogether/backend/service/SearchService.java
  src/main/java/com/pintogether/backend/service/SqlPlaceSearchImpl.java
Labels: enhancement
